// Code generated by logcopter-gen; DO NOT EDIT.

package goals

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.tactician.pkg.commands.goals")
